/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package taint.sample.gradle;

import org.checkerframework.checker.units.qual.A;
import org.junit.Test;

import java.util.ArrayList;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        ArrayListPage<String> alp = new ArrayListPage<>(new ArrayList<>());
    }
}
